### ISSUE TITLE
Expired Iterator Exception

### ISSUE THREAD

**Issue by juliensydney** [theburningmonk/ReactoKinesix#56]
I am experiencing the following issue when the iterator becomes expired (after 5 minutes) and records are not being processed:

2015-07-03 11:56:58,941 [9] ERROR KinesisUtils [(null)] - Failed to get records from stream [App], shard [shardId-000000000000]
Amazon.Kinesis.Model.ExpiredIteratorException: Iterator expired. The iterator was created at time Thu Jul 02 12:57:57 UTC 2015 while right now it is Fri Jul 03 03:56:58 UTC 2015 which is further in the future than the tolerated delay of 300000 milliseconds. --->

**Comment by theburningmonk** [comment]
Hi, sorry for late reply, got back from holiday in Japan this week and been bogged down with work stuff since.

From the error message it looks pretty odd, as it claims the iterator was created almost a day before, and there are couple of inconsistencies in timestamp here:
- error message said iterator was created at **Jul 02 12:57:57 UTC 2015**
- you said it expired after 5 mins
- timestamp of error message is **2015-17-03 11:56:58** which I presume is UTC?
- error message said `right now` is **Jul 03 03:56:58 UTC 2015**

Can you verify the timestamp of the log message, if it's in UTC? And what is the timezone the server is configured with?

**Comment by tomhall** [comment]
Hi @theburningmonk - the server timezone is UTC, log4net is logging %date rather than %utcdate (hence mismatch on log entry). Same error occurring today: 

`2015-07-22 23:13:43,182 [393] ERROR KinesisUtils [(null)] - Failed to get records from stream [App], shard [shardId-000000000002]
Amazon.Kinesis.Model.ExpiredIteratorException: Iterator expired. The iterator was created at time Mon Jul 13 05:16:47 UTC 2015 while right now it is Wed Jul 22 23:13:42 UTC 2015 which is further in the future than the tolerated delay of 300000 milliseconds. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.`

`2015-07-22 23:15:27,463 [466] ERROR KinesisUtils [(null)] - Failed to get records from stream [App], shard [shardId-000000000002]
Amazon.Kinesis.Model.ExpiredIteratorException: Iterator expired. The iterator was created at time Mon Jul 13 05:16:47 UTC 2015 while right now it is Wed Jul 22 23:15:27 UTC 2015 which is further in the future than the tolerated delay of 300000 milliseconds. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.`

We're trying to diagnose whether this is something our end or in the ReactoKinesix library, any help/ideas much appreciated.

**Comment by theburningmonk** [comment]
Hi so I spent a bit of time looking at this, and my suspicion is that when there are empty receives it's not recording the new iterator it received from Kinesis. So if this goes on for a long time, then it's possible for the iterator to go stale.

Are you seeing activities on the shard where you got this error? ReactoKinesix should be tracking a number of CloudWatch metrics under the 'Reacto-KinesiX' namespace, so you can check those.

**Comment by NeilCross** [comment]
Thanks for the response, we discovered that a cause for this issue was when a single process look took more than 5 minutes.  

We adjusted the ReactoKinesix configuration to retrieve a smaller number of records from Kinesis and minimise the likelihood of a single iteration taking more than 5 minutes.

Optimally the framework would detect this response from Kinesis and begin negotiation for a new iterator token.  Though I do realise that the idea of the process is to get work done quickly, and not have long process iterations, these things may happen in extenuating circumstances.

Also regarding your investigation of empty receives: that's not the scenario we've observed, we have processors on development environments which remain operational even with low volumes of stream ingress.

**Comment by theburningmonk** [comment]
Yup, you're right, the library should handle this and re-negotiate with Kinesis, it should be an easy change too

**Comment by theburningmonk** [comment]
I've pushed a new version v0.5.0 which fixes this issue here by getting a new shard iterator when `ExpiredIteratorException` is caught.

It now also records some more info in the process state table in DynamoDB: 
* a `CheckpointAt` timestamp to give you a better idea when the last checkpoint was made
* `MillisecondsBehindLatest` value that came back from Kinesis to let you know how far you're behind in the stream

**Comment by theburningmonk** [comment]
I'll close this ticket for now, feel free to reopen if you think this problem is still not fixed.
