### ISSUE TITLE
AWSconfigs and hiding credentials

### ISSUE THREAD

**Issue by luck02** [theburningmonk/ReactoKinesix#58]
Just wondering if there's a mechanism buried in the app that allows consumers to use the standard AWSConfigs component to handle most of the configuration (token, secret) etc. Credentials that should be controlled in production etc.

**Comment by theburningmonk** [comment]
You can use the overloaded `CreateNew` method (https://github.com/theburningmonk/ReactoKinesix/blob/develop/src/ReactoKinesiX/Client.fs#L399) and pass in clients for Kinesis, DynamoDB and CloudWatch which you can construct using all the mechanisms that the AWSSDK supports.

For development, we use the [AWSProfileName](http://docs.aws.amazon.com/AWSSdkDocsNET/latest/V2/DeveloperGuide/net-dg-config-creds.html) to provide the credentials so the `AWSClientFactory` is able to instantiate the different clients. For production, the credentials are provided through IAM roles.

In general, the AWSSDK is smart enough to work out where to get credentials from and instead of replicating all of that mechanism I thought it'd be easier to just let you construct the dependencies yourself and pass them in.

**Comment by luck02** [comment]
Makes sense, I saw that constructor but my eyes aren't used to reading F# code so the brain didn't register it correctly.

Appologies.
